apiVersion: apps/v1
kind: Deployment
metadata:
  name: major-deployment-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: major-app-api
  template:
    metadata:
      labels:
        app: major-app-api
    spec:
      containers:
        - name: major-container-api
          image: docker.io/apptemp/major
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
          startupProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: major-service-api
spec:
  selector:
    app: major-app-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
