apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Solarleaf/liatrio-apprentice
    targetRevision: ArgoCD
    path: ArgoManifest

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  retry:
    limit: 2
    backoff:
      duration: 15s
      factor: 3
      maxDuration: 3m0s
