apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  annotations:
    # argocd-image-updater.argoproj.io/image-list: apptemp/liatrio*
    argocd-image-updater.argoproj.io/apptemp_liatrio.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/source-type: directory
    argocd-image-updater.argoproj.io/apptemp_liatrio.ignore-tags: latest
    # argocd-image-updater.argoproj.io/source-type: kustomize
    # argocd-image-updater.argoproj.io/write-back-target: ArgoManifest

spec:
  project: default

  source:
    repoURL: git@github.com:Solarleaf/liatrio-apprentice.git
    targetRevision: ArgoCD
    path: ArgoManifest/
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
