apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: apptemp/liatrio
    argocd-image-updater.argoproj.io/apptemp_liatrio.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-creds
    argocd-image-updater.argoproj.io/write-back-method: git:secret:git-ssh-key
    # argocd-image-updater.argoproj.io/apptemp_liatrio.force-update: "true"

spec:
  project: default

  source:
    repoURL: git@github.com:Solarleaf/liatrio-apprentice.git
    directory:
      recurse: true
    # repoURL: https://github.com/Solarleaf/liatrio-apprentice
    targetRevision: ArgoCD
    path: ArgoManifest/

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
