apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: apptemp-liatrio
    argocd-image-updater.argoproj.io/apptemp_liatrio.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/source-type: directory
    argocd-image-updater.argoproj.io/apptemp_liatrio.ignore-tags: latest
    # argocd-image-updater.argoproj.io/source-type: kustomize
    # argocd-image-updater.argoproj.io/write-back-target: ArgoManifest

spec:
  project: default

  source:
    repoURL: git@github.com:Solarleaf/liatrio-apprentice.git
    # repoURL: https://github.com/Solarleaf/liatrio-apprentice
    targetRevision: ArgoCD
    path: ArgoManifest/
    # sshPRivateKeySecret:
    #   name: git-ssh-key
    #   key: sshPrivateKey
    # usernameSecret:
    #   name: argocd-repo-creds
    #   key: username
    # passwordSecret:
    #   name: argocd-repo-creds
    #   key: password

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
