apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster-1
ports:
  - port: 8081:8081
    nodeFilters:
      - loadbalancer
  - port: 8080:443
    nodeFilters:
      - loadbalancer
  - port: 8082:8082
    nodeFilters:
      - loadbalancer