# deployment.yaml Main File

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-deployment-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: liatrio-app-api
  template:
    metadata:
      labels:
        app: liatrio-app-api
    spec:
      containers:
        - name: liatrio-container-api
          image: docker.io/apptemp/liatrio:latest
          ports:
            - containerPort: 80
          # Environmental Variables
          env:
            - name: PORT
              value: "80"
          # Probes
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          # Resources
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
# Have this in same file for less screen changing
# Namespaces in separate for better pratices, no namespace req, names easy
apiVersion: v1
kind: Service
metadata:
  name: liatrio-service-api
spec:
  selector:
    app: liatrio-app-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
# Have this in same file for less screen changing
# kubectl run -i --tty load-generator --image=busybox --restart=Never -n dev -- /bin/sh -c "while true; do wget -q -O- http://liatrio-service-api.dev.svc.cluster.local; done"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: liatrio-hpa-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: liatrio-deployment-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
