apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-deployment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liatrio-app-api
  template:
    metadata:
      labels:
        app: liatrio-app-api
    spec:
      containers:
        - name: liatrio-container-api
          image: docker.io/apptemp/liatrio:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: liatrio-service-api
spec:
  selector:
    app: liatrio-app-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
