# Designed to trigger a rollout
spec:
  template:
    metadata:
      annotations:
        test: "Test on pod to trigger rollout"


# Designed to max the Horizontal Pod Autoscaling
spec:
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 1
