# HPA is in two spots, just for testing purposes
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: liatrio-hpa-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: liatrio-deployment-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
