name: -Test This was Trying to run it by itself Apprenticeship App Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@b6b3837bb48d74422173407098b4ad9f9e40ace7