name: -Test trying out matrix, checkout, and npm script style.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node index.js
    # This needs to be turned on and package.json also needs 
    #     "build": "node index.js"
#    - run: npm run build --if-present
#   - run: npm test