name: Running By Itself
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker Image
      run: docker compose up --build
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

