# name: Apprentice Test - Running Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    # Checks out the Repo code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t liatrio .

      - name: Run Docker
        run: docker run -d -p 80:80 liatrio

      - name: run Liatrio 6 tests
        uses: liatrio/github-actions/apprentice-action@v1.0.0
        with:
          ref: '0b41561cca6822cc8d880fe0e49e7807a41fdf91'

      - name: Log in to Docker Hub
        # If success just in case an if: failure() is every used
        # Want to make sure that everything worked before starting the upload process
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Timestamp
        run: echo "BUILD_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      # Creaetes a latest and a time stamped version making manual rollbacks easier if needed
      - name: Tag Docker Image
        if: success()
        run: |
          docker tag liatrio apptemp/liatrio:latest
          docker tag liatrio apptemp/liatrio:${BUILD_TIME}

      - name: Push Docker Image
        if: success()
        run: |
          docker push apptemp/liatrio:latest
          docker push apptemp/liatrio:${BUILD_TIME}
