name: Apprentice GitHub Actions

on:
  push:
    branches:
      - main
      - GitHub
  pull_request:
    branches: [main]

# Prevent Multiple Actions from happening at once on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  IMAGE_NAME: liatrio-api
  DOCKER_REPO: apptemp/liatrio
  PORT: 80
jobs:
  liatriotests: # Name Required for passing the pull request checks
    # build:
    # Runner using version
    runs-on: ubuntu-24.04
    # Checks out the Repo code
    steps:
      # This was used for Best Practices: Version Control. STatus checks to pass before merging
      # - name: failing it
      #   run: exit 1

      # checkout@v4 using Sha 3-13-25
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Run Docker
        run: docker run -d -p $PORT:$PORT $IMAGE_NAME

      # liatrio/github-actions/apprentice-action@v1.0.0 3-13-25
      - name: run Liatrio 6 tests
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Log in to Docker Hub
        # If success just in case an if: failure() is every used
        # Want to make sure that everything worked before starting the upload process
        if: success()
        # uses: docker/login-action@v2 3-13-25
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag as Commit Sha
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
      # Creaetes a latest and a time stamped version making manual rollbacks easier if needed
      - name: Tag Docker Image
        if: success()
        run: |
          docker tag $IMAGE_NAME $DOCKER_REPO:latest
          docker tag $IMAGE_NAME $DOCKER_REPO:${IMAGE_TAG}

      - name: Push Docker Image
        if: success()
        run: |
          docker push $DOCKER_REPO:latest
          docker push $DOCKER_REPO:${IMAGE_TAG}
  # Per Best Practices this would be a separate file. To avoid Screen swaps keeping it in same file
  #  on:
  #   workflow_run:
  #     workflows: ["liatriotests"]
  #     types:
  #       - completed

  GCloud:
    # build:
    needs: liatriotests
    # Runner using version
    runs-on: ubuntu-24.04
    # Checks out the Repo code
    permissions:
      contents: read
    steps:
      # This was used for Best Practices: Version Control. STatus checks to pass before merging
      # - name: failing it
      #   run: exit 1

      # checkout@v4 using Sha 3-13-25
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # - uses: "google-github-actions/auth@v2"
      - uses: "google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f"
        with:
          credentials_json: "${{ secrets.GOGLE_CREDS }}"

      # uses: google-github-actions/setup-gcloud@v2 3-13-25
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a

      - name: Set project
        run: gcloud config set project "${{ secrets.PROJECT_ID }}"
      # - name: Kubernetes Actions
      # gcloud services enable cloudresourcemanager.googleapis.com
      # gcloud services enable container.googleapis.com
