name: Other Methods

on:
  push:
    branches: [ "main" ]

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCE_SA_KEY }}'

      - name: SSH into Compute Engine
        uses: google-github-actions/ssh-compute@v1
        with:
          instance_name: 'celiatrio'
          zone: 'us-west1-b'
          user: 'lunar'
          ssh_private_key: '${{ secrets.GCE_PRIVATE }}'
          command: |
            'echo Hello world'
            ls /home
            ls


      - name: "Installs"
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install git
          sudo snap install docker
          git clone https://github.com/Solarleaf/liatrio-apprentice.git

      - name: "Run Node"
        run: |
          cd liatrio-apprentice
          sudo docker compose up --build -d
          wget http://127.17.0.1:80
          cat index.html ; echo
      - name: "Clean Environment"
        run: |
          sleep 20
          rm index.html || true
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker images
          sudo docker ps -a
          sudo docker container prune -f || true
          sudo docker image prune --all -f || true

