# name: Terminal

on:
  workflow_dispatch:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow won't run unless triggered manually"
# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Google Auth
#         id: auth
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCE_SA_KEY }}'

#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v2'
#         with:
#           version: '>= 363.0.0'
#       - name: 'Use gcloud CLI'
#         run: 'gcloud info'
#       - name: "Info"
#         run: |
#           gcloud auth list
#           gcloud config set project liatrio-421422
#           ls

#       - name: "Installs"
#         run: |
#           sudo apt-get update
#           sudo apt-get upgrade -y
#           sudo apt-get install git
#           sudo snap install docker
#           git clone https://github.com/Solarleaf/liatrio-apprentice.git

#       - name: "Run Node"
#       # sudo docker compose up --build -d
#         run: |
#           cd liatrio-apprentice
#           docker compose build --no-cache
#           docker compose up -d

#           wget http://127.17.0.1:80
#           cat index.html ; echo
#       - name: "Clean Environment"
#         run: |
#           sleep 20
#           rm index.html || true
#           sudo docker stop $(sudo docker ps -q) || true
#           sudo docker images
#           sudo docker ps -a
#           sudo docker container prune -f || true
#           sudo docker image prune --all -f || true
