name: Increment Action Variable

on:
  workflow_dispatch:
  push:
    branches:
      - Version

permissions:
  actions: write # Ensure GitHub Actions can modify variables
  contents: read # Allow repository read access

jobs:
  increment-version:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current version (if exists)
        id: get-version
        run: |
          CURRENT_VERSION=${{ vars.TESTING_THIS }}
          echo "Current version: $CURRENT_VERSION"
          NEW_VERSION=$((CURRENT_VERSION + 1))
          echo "New version: $NEW_VERSION"

          # Store the new version for later use
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update GitHub environment variable
        run: |
          gh variable set TESTING_THIS --body "$NEW_VERSION" --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
