name: Increment Action Variable

on:
  workflow_dispatch:
  push:
    branches:
      - Version

jobs:
  increment-version:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure GitHub CLI is available
        run: gh --version

      - name: Get current version (if exists)
        id: get-version
        continue-on-error: true
        run: |
          echo "${{ vars.TESTING_THIS }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
