name: Apprenticeship App Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: node index.js
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
