name: Increment Branch Version

on:
  push:
    branches:
      - "Version"

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures full repo history, including .git/config

      - name: Set and Increment Version Tag
        run: |
          # Extract branch name and normalize it
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')

          # Ensure version file exists
          VERSION_FILE="version.txt"
          if [ ! -f $VERSION_FILE ]; then
            echo "0.0.0" > $VERSION_FILE
          fi

          # Read current version from version.txt or .git/config (fallback)
          CURRENT_VERSION=$(git config --get branch.${BRANCH_NAME}.version || cat $VERSION_FILE || echo "0.0.0")

          # Function to increment version
          increment_version() {
            local version=$1
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch + 1))
            echo "${major}.${minor}.${patch}"
          }

          # Get new incremented version
          NEW_VERSION=$(increment_version "$CURRENT_VERSION")

          # Save new version to .git/config and version.txt
          git config --global branch.${BRANCH_NAME}.version "${NEW_VERSION}"
          echo "${NEW_VERSION}" > $VERSION_FILE

          # Export new version to GitHub Actions environment
          echo "NEW_VERSION=${BRANCH_NAME}-${NEW_VERSION}" >> $GITHUB_ENV
          echo "NEW_VERSION=${BRANCH_NAME}-${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Commit and Push Updated Version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Ensure changes are tracked
          git add version.txt
          git commit -m "Update version for ${BRANCH_NAME} to ${NEW_VERSION}" || echo "No changes to commit"
          git push origin ${GITHUB_REF#refs/heads/} || echo "No changes to push"

      - name: Display New Version
        run: |
          echo "Branch ${BRANCH_NAME} new version: ${NEW_VERSION}"
